using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Weather
{
    public class CountriesModels
    {
        public CountriesModels()
        { }
       
        public List<string> China { get; set; }
        public List<string> Japan { get; set; }
        public List<string> Thailand { get; set; }
        public List<string> UnitedStates { get; set; }
        public List<string> India { get; set; }
        public List<string> Malaysia { get; set; }
        public List<string> RepublicofKorea { get; set; }
        public List<string> HongKong { get; set; }
        public List<string> Taiwan { get; set; }
        public List<string> Philippines { get; set; }
        public List<string> Australia { get; set; }
        public List<string> Vietnam { get; set; }
        public List<string> Russia { get; set; }
        public List<string> France { get; set; }
        public List<string> _ { get; set; }
        public List<string> Germany { get; set; }
        public List<string> Israel { get; set; }
        public List<string> Sweden { get; set; }
        public List<string> Italy { get; set; }
        public List<string> Netherlands { get; set; }
        public List<string> Greece { get; set; }
        public List<string> Spain { get; set; }
        public List<string> Austria { get; set; }
        public List<string> UnitedKingdom { get; set; }
        public List<string> Belgium { get; set; }
        public List<string> UnitedArabEmirates { get; set; }
        public List<string> Kazakhstan { get; set; }
        public List<string> Portugal { get; set; }
        public List<string> SaudiArabia { get; set; }
        public List<string> Denmark { get; set; }
        public List<string> Slovenia { get; set; }
        public List<string> Iran { get; set; }
        public List<string> Norway { get; set; }
        public List<string> Mexico { get; set; }
        public List<string> Canada { get; set; }
        public List<string> Syria { get; set; }
        public List<string> Ukraine { get; set; }
        public List<string> Cyprus { get; set; }
        public List<string> CzechRepublic { get; set; }
        public List<string> Switzerland { get; set; }
        public List<string> Iraq { get; set; }
        public List<string> Turkey { get; set; }
        public List<string> Romania { get; set; }
        public List<string> Lebanon { get; set; }
        public List<string> Hungary { get; set; }
        public List<string> Georgia { get; set; }
        public List<string> Brazil { get; set; }
        public List<string> Azerbaijan { get; set; }
        public List<string> Palestine { get; set; }
        public List<string> RepublicofLithuania { get; set; }
        public List<string> Oman { get; set; }
        public List<string> Slovakia { get; set; }
        public List<string> Serbia { get; set; }
        public List<string> Finland { get; set; }
        public List<string> Iceland { get; set; }
        public List<string> RepublicofMoldova { get; set; }
        public List<string> Bulgaria { get; set; }
        public List<string> Macedonia { get; set; }
        public List<string> Liechtenstein { get; set; }
        public List<string> Jersey { get; set; }
        public List<string> Poland { get; set; }
        public List<string> Ireland { get; set; }
        public List<string> Croatia { get; set; }
        public List<string> BosniaandHerzegovina { get; set; }
        public List<string> Estonia { get; set; }
        public List<string> Latvia { get; set; }
        public List<string> HashemiteKingdomofJordan { get; set; }
        public List<string> Kyrgyzstan { get; set; }
        public List<string> RÃunion { get; set; }
        public List<string> IsleofMan { get; set; }
        public List<string> Libya { get; set; }
        public List<string> Luxembourg { get; set; }
        public List<string> Armenia { get; set; }
        public List<string> BritishVirginIslands { get; set; }
        public List<string> Yemen { get; set; }
        public List<string> Belarus { get; set; }
        public List<string> Gibraltar { get; set; }
        public List<string> Kenya { get; set; }
        public List<string> Chile { get; set; }
        public List<string> Qatar { get; set; }
        public List<string> Kuwait { get; set; }
        public List<string> Guadeloupe { get; set; }
        public List<string> Martinique { get; set; }
        public List<string> FrenchGuiana { get; set; }
        public List<string> DominicanRepublic { get; set; }
        public List<string> Guam { get; set; }
        public List<string> USVirginIslands { get; set; }
        public List<string> PuertoRico { get; set; }
        public List<string> Mongolia { get; set; }
        public List<string> NewZealand { get; set; }
        public List<string> Singapore { get; set; }
        public List<string> Indonesia { get; set; }
        public List<string> Nepal { get; set; }
        public List<string> PapuaNewGuinea { get; set; }
        public List<string> Pakistan { get; set; }
        public List<string> Panama { get; set; }
        public List<string> CostaRica { get; set; }
        public List<string> Peru { get; set; }
        public List<string> Belize { get; set; }
        public List<string> Nigeria { get; set; }
        public List<string> Venezuela { get; set; }
        public List<string> Bahamas { get; set; }
        public List<string> Morocco { get; set; }
        public List<string> Colombia { get; set; }
        public List<string> Seychelles { get; set; }
        public List<string> Barbados { get; set; }
        public List<string> Egypt { get; set; }
        public List<string> Argentina { get; set; }
        public List<string> Brunei { get; set; }
        public List<string> Bahrain { get; set; }
        public List<string> Aruba { get; set; }
        public List<string> SaintLucia { get; set; }
        public List<string> Bangladesh { get; set; }
        public List<string> Tokelau { get; set; }
        public List<string> Cambodia { get; set; }
        public List<string> Macao { get; set; }
        public List<string> Maldives { get; set; }
        public List<string> Afghanistan { get; set; }
        public List<string> NewCaledonia { get; set; }
        public List<string> Fiji { get; set; }
        public List<string> WallisandFutuna { get; set; }
        public List<string> Albania { get; set; }
        public List<string> Uzbekistan { get; set; }
        public List<string> Montenegro { get; set; }
        public List<string> NorthKorea { get; set; }
        public List<string> VaticanCity { get; set; }
        public List<string> Antarctica { get; set; }
        public List<string> Bermuda { get; set; }
        public List<string> CuraÃao { get; set; }
        public List<string> Ecuador { get; set; }
        public List<string> SouthAfrica { get; set; }
        public List<string> SaintKittsandNevis { get; set; }
        public List<string> Samoa { get; set; }
        public List<string> Bolivia { get; set; }
        public List<string> Guernsey { get; set; }
        public List<string> Malta { get; set; }
        public List<string> Tajikistan { get; set; }
        public List<string> Zimbabwe { get; set; }
        public List<string> Liberia { get; set; }
        public List<string> Ghana { get; set; }
        public List<string> Tanzania { get; set; }
        public List<string> Zambia { get; set; }
        public List<string> Madagascar { get; set; }
        public List<string> Angola { get; set; }
        public List<string> Namibia { get; set; }
        public List<string> IvoryCoast { get; set; }
        public List<string> Sudan { get; set; }
        public List<string> Uganda { get; set; }
        public List<string> Cameroon { get; set; }
        public List<string> Malawi { get; set; }
        public List<string> Gabon { get; set; }
        public List<string> Mali { get; set; }
        public List<string> Benin { get; set; }
        public List<string> Chad { get; set; }
        public List<string> Botswana { get; set; }
        public List<string> CapeVerde { get; set; }
        public List<string> Rwanda { get; set; }
        public List<string> RepublicoftheCongo { get; set; }
        public List<string> Mozambique { get; set; }
        public List<string> Gambia { get; set; }
        public List<string> Lesotho { get; set; }
        public List<string> Mauritius { get; set; }
        public List<string> Algeria { get; set; }
        public List<string> Guinea { get; set; }
        public List<string> Congo { get; set; }
        public List<string> Swaziland { get; set; }
        public List<string> BurkinaFaso { get; set; }
        public List<string> SierraLeone { get; set; }
        public List<string> Somalia { get; set; }
        public List<string> Niger { get; set; }
        public List<string> CentralAfricanRepublic { get; set; }
        public List<string> Togo { get; set; }
        public List<string> Burundi { get; set; }
        public List<string> EquatorialGuinea { get; set; }
        public List<string> SouthSudan { get; set; }
        public List<string> Senegal { get; set; }
        public List<string> Mauritania { get; set; }
        public List<string> Djibouti { get; set; }
        public List<string> Comoros { get; set; }
        public List<string> Tunisia { get; set; }
        public List<string> Mayotte { get; set; }
        public List<string> Bhutan { get; set; }
        public List<string> Greenland { get; set; }
        public List<string> Kosovo { get; set; }
        public List<string> CaymanIslands { get; set; }
        public List<string> Jamaica { get; set; }
        public List<string> Guatemala { get; set; }
        public List<string> MarshallIslands { get; set; }
        public List<string> Monaco { get; set; }
        public List<string> Anguilla { get; set; }
        public List<string> Grenada { get; set; }
        public List<string> Paraguay { get; set; }
        public List<string> Montserrat { get; set; }
        public List<string> TurksandCaicosIslands { get; set; }
        public List<string> AntiguaandBarbuda { get; set; }
        public List<string> Tuvalu { get; set; }
        public List<string> FrenchPolynesia { get; set; }
        public List<string> SolomonIslands { get; set; }
        public List<string> Vanuatu { get; set; }
        public List<string> Suriname { get; set; }
        public List<string> CookIslands { get; set; }
        public List<string> Kiribati { get; set; }
        public List<string> Niue { get; set; }
        public List<string> Tonga { get; set; }
        public List<string> FrenchSouthernTerritories { get; set; }
        public List<string> NorfolkIsland { get; set; }
        public List<string> Turkmenistan { get; set; }
        public List<string> PitcairnIslands { get; set; }
        public List<string> SanMarino { get; set; }
        public List<string> Ãland { get; set; }
        public List<string> FaroeIslands { get; set; }
        public List<string> SvalbardandJanMayen { get; set; }
        public List<string> CocosKeelingIslands { get; set; }
        public List<string> Nauru { get; set; }
        public List<string> SouthGeorgiaandtheSouthSandwichIslands { get; set; }
        public List<string> USMinorOutlyingIslands { get; set; }
        public List<string> SintMaarten { get; set; }
        public List<string> GuineaBissau { get; set; }
        public List<string> SaintMartin { get; set; }
        public List<string> SaintVincentandtheGrenadines { get; set; }
        public List<string> SaintPierreandMiquelon { get; set; }
        public List<string> SaintBarthÃlemy { get; set; }
        public List<string> Dominica { get; set; }
        public List<string> SÃoTomÃandPrÃncipe { get; set; }
        public List<string> FalklandIslands { get; set; }
        public List<string> NorthernMarianaIslands { get; set; }
        public List<string> EastTimor { get; set; }
        public List<string> Bonaire { get; set; }
        public List<string> AmericanSamoa { get; set; }
        public List<string> FederatedStatesofMicronesia { get; set; }
        public List<string> Palau { get; set; }
        public List<string> Guyana { get; set; }
        public List<string> Honduras { get; set; }
        public List<string> Nicaragua { get; set; }
        public List<string> ElSalvador { get; set; }
        public List<string> Andorra { get; set; }
        public List<string> MyanmarBurma { get; set; }
        public List<string> SriLanka { get; set; }
        public List<string> Haiti { get; set; }
        public List<string> TrinidadandTobago { get; set; }
        public List<string> Laos { get; set; }
        public List<string> Uruguay { get; set; }
        public List<string> Eritrea { get; set; }
        public List<string> Cuba { get; set; }
        public List<string> SaintHelena { get; set; }
        public List<string> ChristmasIsland { get; set; }
        public List<string> Ethiopia { get; set; }
        public string BritishIndianOceanTerritory { get; set; }





    }

}
